FROM recommender-base

LABEL org.opencontainers.image.source=https://github.com/habh2/recommender-system

COPY preference/extract_embeddings.py preference/extract_embeddings.py
COPY preference/train_topic_model.py preference/train_topic_model.py

CMD ["python", "preference/train_topic_model.py"]
