FROM recommender-base

LABEL org.opencontainers.image.source=https://github.com/habh2/paper-recommender-system

COPY preference/compute_distributions.py preference/compute_distributions.py

CMD ["python", "preference/compute_distributions.py"]
