FROM recommender-base

LABEL org.opencontainers.image.source=https://github.com/habh2/recommender-system

COPY preference/train_preference_model.py preference/train_preference_model.py
COPY preference/evaluate.py preference/evaluate.py

CMD ["python", "preference/train_preference_model.py"]
